spring.application.name=api-gateway
server.port=4004
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web=DEBUG
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.webmvc.routes.enabled=true
spring.cloud.gateway.routes[0].id=patient-service
spring.cloud.gateway.routes[0].uri=http://host.docker.internal:8004
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/patients/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1



